services:
  cassandra-1:
    container_name: "cassandra-1"
    image: cassandra:4.1
    volumes:
      - cassandra-data-1:/var/lib/cassandra
    ports:
      - 7020:7000
      - 9045:9042
    environment:
      - CASSANDRA_USER=cassandra
      - CASSANDRA_PASSWORD=cassandra@123
      - CASSANDRA_START_RPC=true
      - CASSANDRA_RPC_ADDRESS=0.0.0.0
      - CASSANDRA_LISTEN_ADDRESS=auto
      - CASSANDRA_CLUSTER_NAME=distribcluster
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=distribdc-1
    networks:
      - cassandra-network
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'describe cluster' || exit 1"]
      interval: 10s
      start_period: 40s
      timeout: 5s
      retries: 5

  cassandra-2:
    container_name: "cassandra-2"
    image: cassandra:4.1
    volumes:
      - cassandra-data-2:/var/lib/cassandra
    ports:
      - 9043:9042
    environment:
      - CASSANDRA_USER=cassandra
      - CASSANDRA_PASSWORD=cassandra@123
      - CASSANDRA_START_RPC=true
      - CASSANDRA_RPC_ADDRESS=0.0.0.0
      - CASSANDRA_LISTEN_ADDRESS=auto
      - CASSANDRA_BROADCAST_ADDRESS=cassandra-2
      - CASSANDRA_CLUSTER_NAME=distribcluster
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=distribdc-1
      - CASSANDRA_SEEDS=cassandra-1
    depends_on:
      cassandra-1:
        condition: service_healthy
    networks:
      - cassandra-network
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'describe cluster' || exit 1"]
      interval: 10s
      start_period: 40s
      timeout: 5s
      retries: 5

  cassandra-3:
    container_name: "cassandra-3"
    image: cassandra:4.1
    volumes:
      - cassandra-data-3:/var/lib/cassandra
    ports:
      - 9044:9042
    environment:
      - CASSANDRA_USER=cassandra
      - CASSANDRA_PASSWORD=cassandra@123
      - CASSANDRA_START_RPC=true
      - CASSANDRA_RPC_ADDRESS=0.0.0.0
      - CASSANDRA_LISTEN_ADDRESS=auto
      - CASSANDRA_BROADCAST_ADDRESS=cassandra-3
      - CASSANDRA_CLUSTER_NAME=distribcluster
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=distribdc-1
      - CASSANDRA_SEEDS=cassandra-1
    depends_on:
      cassandra-2:
        condition: service_healthy
    networks:
      - cassandra-network
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'describe cluster' || exit 1"]
      interval: 10s
      start_period: 40s
      timeout: 5s
      retries: 5

  python-app:
    container_name: python-app
    build: .
    depends_on:
      cassandra-1:
        condition: service_healthy
      cassandra-2:
        condition: service_healthy
      cassandra-3:
        condition: service_healthy
    networks:
      - cassandra-network

volumes:
  cassandra-data-1:
  cassandra-data-2:
  cassandra-data-3:

networks:
  cassandra-network:
    driver: bridge
