services:
  redis-master:
    image: redis:8.2
    container_name: redis-master
    command: redis-server --appendonly yes --appendfilename "appendonly.aof"
    ports:
      - "7379:6379"
    volumes:
      - redis-master-data:/data
    networks:
      - redis-network

  redis-replica1:
    image: redis:8.2
    container_name: redis-replica1
    command: redis-server --appendonly yes --replicaof redis-master 6379
    ports:
      - "6380:6379"
    volumes:
      - redis-replica1-data:/data
    networks:
      - redis-network
    depends_on:
      - redis-master

  redis-replica2:
    image: redis:8.2
    container_name: redis-replica2
    command: redis-server --appendonly yes --replicaof redis-master 6379
    ports:
      - "6381:6379"
    volumes:
      - redis-replica2-data:/data
    networks:
      - redis-network
    depends_on:
      - redis-master

  python-app:
    container_name: python-app
    build: .
    depends_on:
      - redis-master
      - redis-replica1
      - redis-replica2
    networks:
      - redis-network

volumes:
  redis-master-data:
  redis-replica1-data:
  redis-replica2-data:

networks:
  redis-network:
    driver: bridge
